server:
  port: 9108
eureka:
  client:
    service-url:
      defaultZone: http://120.77.241.51:8762/eureka
  instance:
    prefer-ip-address: true
    ip-address: 49.123.79.89
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
spring:
  application:
    name: mall-category
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://49.123.79.89:3306/mall?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
#  redis:
#    host: 120.77.241.51
#    password: 123456
#    timeout: 10000ms
#    jedis:
#      pool:
#        max-active: 32
#        max-wait: 10000ms
#        max-idle: 32
#        min-idle: 0
mybatis:
  mapper-locations: classpath:com/lc/mallcategory/dao/mapper/*.xml
  type-aliases-package: classpath:com.lc.mallcategory.entity
