spring:
  application:
    name: mall-user
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.69.161.154:3306/mall?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  redis:
    host: 120.77.241.51
    password: 123456
    timeout: 10000ms
    jedis:
      pool:
        max-active: 32
        max-wait: 10000ms
        max-idle: 32
        min-idle: 0
  jpa:
    show-sql: true
ribbon:
  eureka:
    enabled: true
eureka:
  instance:
    prefer-ip-address: true
    ip-address: 10.69.161.154 #49.123.79.89 #10.69.161.154
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://120.77.241.51:8762/eureka
server:
  port: 9008
logging:
  config: classpath:logback.xml
mybatis:
  mapper-locations: classpath:com/lc/malluser/dao/mapper/*.xml
  type-aliases-package: com.lc.malluser.entity
zk:
  host: 120.77.241.51