
server:
  port: 9009
eureka:
  client:
    service-url:
      defaultZone: http://120.77.241.51:8762/eureka
  instance:
    prefer-ip-address: true
    ip-address: 10.69.182.198
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
spring:
  application:
    name: mall-product
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.69.182.198:3306/mall?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  redis:
    host: 120.77.241.51
    password: 123456
    timeout: 10000ms
    jedis:
      pool:
        max-active: 32
        max-wait: 10000ms
        max-idle: 32
        min-idle: 0
  jpa:
    show-sql: true
  rabbitmq:
    host: 120.77.241.51
    port: 5672
    username: guest
    password: guest
mybatis:
  mapper-locations: classpath:com/lc/mallproduct/dao/*.xml
  type-aliases-package: classpath:com.lc.mallproduct.entity